//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "player_played_quiz")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub player_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub quiz_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::player::Entity",
        from = "Column::PlayerId",
        to = "super::player::Column::TelegramId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Player,
    #[sea_orm(
        belongs_to = "super::quiz::Entity",
        from = "Column::QuizId",
        to = "super::quiz::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Quiz,
}

impl Related<super::player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Player.def()
    }
}

impl Related<super::quiz::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Quiz.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
