//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "player")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub telegram_id: i32,
    pub score: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::player_poll_answer::Entity")]
    PlayerPollAnswer,
    #[sea_orm(has_many = "super::player_played_quiz::Entity")]
    PlayerPlayedQuiz,
}

impl Related<super::player_poll_answer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerPollAnswer.def()
    }
}

impl Related<super::player_played_quiz::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerPlayedQuiz.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
