//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub use super::chat::Entity as Chat;
pub use super::game::Entity as Game;
pub use super::player::Entity as Player;
pub use super::poll::Entity as Poll;
pub use super::question::Entity as Question;
pub use super::question_option::Entity as QuestionOption;
