//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "question")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub text: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::question_option::Entity")]
    QuestionOption,
}

impl Related<super::question_option::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuestionOption.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
