//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "quiz")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub text: String,
    pub correct_option: String,
    pub option2: String,
    pub option3: String,
    pub option4: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::player_played_quiz::Entity")]
    PlayerPlayedQuiz,
}

impl Related<super::player_played_quiz::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerPlayedQuiz.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
